import React from 'react';
import Link from 'next/link';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans pb-24">
      <header className="bg-white border-b border-slate-200 py-6">
        <div className="max-w-4xl mx-auto px-4 flex items-center justify-between">
          <Link href="/" className="font-extrabold tracking-widest text-slate-900 text-lg">DOCSLIP</Link>
          <Link href="/" className="text-sm font-medium text-slate-500 hover:text-blue-600">Return Home</Link>
        </div>
      </header>
      <main className="max-w-3xl mx-auto px-4 pt-16">
        <h1 className="text-4xl font-extrabold text-slate-900 mb-4">Privacy Policy</h1>
        <div className="prose max-w-none space-y-6 text-slate-600 leading-relaxed mt-8">
           <p>DocSlip is configured as a compliance and verification tool for court-approved providers. Under the Complavion ecosystem, we mandate minimal data retention to satisfy audit trail requirements.</p>
           <h3 className="text-xl font-bold text-slate-900 mt-8 mb-3">Data Collection</h3>
           <p>We log participant names, course details, and immutable attendance timestamps as generated by authorized program providers. This forms an append-only ledger optimized for CJIS-style compliance environments.</p>
           <h3 className="text-xl font-bold text-slate-900 mt-8 mb-3">Data Distribution</h3>
           <p>DocSlip strictly manages tenant boundaries. Participants' data is exclusively bound to the originating Provider organization and never aggregated or sold. Verifications are only accessible through secure, randomly-generated cryptographic URLs intended for court submission.</p>
        </div>
      </main>
    </div>
  );
}
